# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

epi_spread <- function(contact_matrix, demography_vector, p_susceptibility, susceptibility) {
    .Call('_testrcppeigen_epi_spread', PACKAGE = 'testrcppeigen', contact_matrix, demography_vector, p_susceptibility, susceptibility)
}

getTensor <- function() {
    .Call('_testrcppeigen_getTensor', PACKAGE = 'testrcppeigen')
}

#' @export
somefun <- function() {
    .Call('_testrcppeigen_somefun', PACKAGE = 'testrcppeigen')
}

#' @export
tensor_op <- function(mat) {
    invisible(.Call('_testrcppeigen_tensor_op', PACKAGE = 'testrcppeigen', mat))
}

#' @export
tensor_op2 <- function(vec) {
    invisible(.Call('_testrcppeigen_tensor_op2', PACKAGE = 'testrcppeigen', vec))
}

#' @export
tensorop3 <- function() {
    invisible(.Call('_testrcppeigen_tensorop3', PACKAGE = 'testrcppeigen'))
}

#' @export
tensor_epidemic <- function(tmax) {
    .Call('_testrcppeigen_tensor_epidemic', PACKAGE = 'testrcppeigen', tmax)
}

#' @export
aging <- function() {
    invisible(.Call('_testrcppeigen_aging', PACKAGE = 'testrcppeigen'))
}

#' @export
tensormult <- function() {
    invisible(.Call('_testrcppeigen_tensormult', PACKAGE = 'testrcppeigen'))
}

