# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate squares.
#'
#' @param x A vector of numbers to square.
#' @return Square of x.
#'
square_rcppeigen_internal <- function(x) {
    .Call('_testrcppeigen_square_rcppeigen_internal', PACKAGE = 'testrcppeigen', x)
}

