# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

epi_spread <- function(contact_matrix, demography_vector, p_susceptibility, susceptibility) {
    .Call('_testrcppeigen_epi_spread', PACKAGE = 'testrcppeigen', contact_matrix, demography_vector, p_susceptibility, susceptibility)
}

getTensor <- function() {
    .Call('_testrcppeigen_getTensor', PACKAGE = 'testrcppeigen')
}

#' @export
somefun <- function() {
    .Call('_testrcppeigen_somefun', PACKAGE = 'testrcppeigen')
}

